create table if not exists projects (
  id integer primary key generated by default as identity,
  title text not null,
  description text not null,
  tech text default '',
  image text default '',
  url text default '',
  github text default,
  featured integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable row level security
alter table projects enable row level security;

-- Create policy for public read access
create policy "Projects are viewable by everyone" on projects
  for select using (true);

-- Create policy for admin insert/update/delete
create policy "Admins can manage projects" on projects
  for all using (true);