create table if not exists messages (
  id integer primary key generated by default as identity,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Enable row level security
alter table messages enable row level security;

-- Create policy for public insert
create policy "Anyone can insert messages" on messages
  for insert with check (true);

-- Create policy for admin read access
create policy "Admins can view messages" on messages
  for select using (true);