begin;

create table if not exists public.profile (
  id integer primary key constraint chk_profile_id check (id = 1),
  name text not null,
  role text not null,
  bio text not null,
  location text not null default '',
  email text not null default '',
  github text not null default '',
  linkedin text not null default '',
  website text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  tech text not null default '',
  image text not null default '',
  url text not null default '',
  github text not null default '',
  featured integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.certifications (
  id integer generated by default as identity primary key,
  title text not null,
  issuer text not null,
  issued_on date,
  credential_url text not null default '',
  image_url text not null default '',
  description text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  path text not null check (path like '/%' and path not like '%?%' and path not like '%#%'),
  referrer_host text not null default '',
  country_code text not null default '' check (char_length(country_code) <= 2),
  browser text not null default '' check (char_length(browser) <= 32),
  browser_version text not null default '' check (char_length(browser_version) <= 6),
  operating_system text not null default '' check (char_length(operating_system) <= 20),
  device_type text not null default '' check (char_length(device_type) <= 16),
  cpu_bucket text not null default '' check (char_length(cpu_bucket) <= 8),
  memory_bucket text not null default '' check (char_length(memory_bucket) <= 20),
  touch_capable boolean not null default false,
  network_type text not null default '' check (char_length(network_type) <= 12),
  data_saver boolean not null default false,
  screen_bucket text not null default '' check (char_length(screen_bucket) <= 12),
  pixel_ratio_bucket text not null default '' check (char_length(pixel_ratio_bucket) <= 8),
  color_depth_bucket text not null default '' check (char_length(color_depth_bucket) <= 16),
  language text not null default '' check (char_length(language) <= 20),
  timezone text not null default '' check (char_length(timezone) <= 64),
  consent_version text not null,
  created_at timestamptz not null default now()
);

alter table public.visits add column if not exists country_code text not null default '';
alter table public.visits add column if not exists browser text not null default '';
alter table public.visits add column if not exists browser_version text not null default '';
alter table public.visits add column if not exists operating_system text not null default '';
alter table public.visits add column if not exists device_type text not null default '';
alter table public.visits add column if not exists cpu_bucket text not null default '';
alter table public.visits add column if not exists memory_bucket text not null default '';
alter table public.visits add column if not exists touch_capable boolean not null default false;
alter table public.visits add column if not exists network_type text not null default '';
alter table public.visits add column if not exists data_saver boolean not null default false;
alter table public.visits add column if not exists screen_bucket text not null default '';
alter table public.visits add column if not exists pixel_ratio_bucket text not null default '';
alter table public.visits add column if not exists color_depth_bucket text not null default '';
alter table public.visits add column if not exists language text not null default '';
alter table public.visits add column if not exists timezone text not null default '';

create index if not exists projects_created_at_idx
  on public.projects (created_at desc);
create index if not exists certifications_issued_on_idx
  on public.certifications (issued_on desc nulls last, created_at desc);
create index if not exists messages_created_at_idx
  on public.messages (created_at desc);
create index if not exists visits_created_at_idx
  on public.visits (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profile_set_updated_at on public.profile;
create trigger profile_set_updated_at
  before update on public.profile
  for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

drop trigger if exists certifications_set_updated_at on public.certifications;
create trigger certifications_set_updated_at
  before update on public.certifications
  for each row execute function public.set_updated_at();

drop trigger if exists messages_set_updated_at on public.messages;
create trigger messages_set_updated_at
  before update on public.messages
  for each row execute function public.set_updated_at();

insert into public.profile (id, name, role, bio, location, email, github, linkedin, website)
values (
  1,
  'Grish Pradhan',
  'Cybersecurity · Forensics · Systems',
  'I build practical tools and secure systems across cybersecurity, forensics, and software.',
  'Lalitpur, Nepal',
  '',
  'https://github.com/Grish-Pradhan',
  'https://www.linkedin.com/in/grish-pradhan-bb60b2279/',
  ''
)
on conflict (id) do nothing;

alter table public.profile enable row level security;
alter table public.projects enable row level security;
alter table public.certifications enable row level security;
alter table public.messages enable row level security;
alter table public.visits enable row level security;

insert into storage.buckets (id, name, public)
values ('portfolio-assets', 'portfolio-assets', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public profiles are viewable by everyone" on public.profile;
drop policy if exists "Admins can update profile" on public.profile;
drop policy if exists "Projects are viewable by everyone" on public.projects;
drop policy if exists "Certifications are viewable by everyone" on public.certifications;
drop policy if exists "Admins can manage projects" on public.projects;
drop policy if exists "Anyone can insert messages" on public.messages;
drop policy if exists "Admins can view messages" on public.messages;
drop policy if exists "Visitors can submit consented page views" on public.visits;

create policy "Public profiles are viewable by everyone"
  on public.profile for select to anon, authenticated
  using (true);

create policy "Projects are viewable by everyone"
  on public.projects for select to anon, authenticated
  using (true);

create policy "Certifications are viewable by everyone"
  on public.certifications for select to anon, authenticated
  using (true);

drop policy if exists "Portfolio assets are publicly viewable" on storage.objects;
create policy "Portfolio assets are publicly viewable"
  on storage.objects for select to anon, authenticated
  using (bucket_id = 'portfolio-assets');

create policy "Visitors can submit consented page views"
  on public.visits for insert to anon, authenticated
  with check (consent_version = '2026-10-02-v3');

revoke all privileges on table public.profile, public.projects, public.certifications, public.messages, public.visits
  from anon, authenticated;
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.profile, public.projects, public.certifications to anon, authenticated;
grant insert on table public.visits to anon, authenticated;
grant all privileges on table public.profile, public.projects, public.certifications, public.messages, public.visits to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;
