begin;

create table if not exists public.profile (
  id integer primary key constraint chk_profile_id check (id = 1),
  name text not null,
  role text not null,
  bio text not null,
  location text not null default '',
  email text not null default '',
  github text not null default '',
  linkedin text not null default '',
  website text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id integer generated by default as identity primary key,
  title text not null,
  description text not null,
  tech text not null default '',
  image text not null default '',
  url text not null default '',
  github text not null default '',
  featured integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id integer generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_created_at_idx
  on public.projects (created_at desc);
create index if not exists messages_created_at_idx
  on public.messages (created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profile_set_updated_at on public.profile;
create trigger profile_set_updated_at
  before update on public.profile
  for each row execute function public.set_updated_at();

drop trigger if exists projects_set_updated_at on public.projects;
create trigger projects_set_updated_at
  before update on public.projects
  for each row execute function public.set_updated_at();

drop trigger if exists messages_set_updated_at on public.messages;
create trigger messages_set_updated_at
  before update on public.messages
  for each row execute function public.set_updated_at();

insert into public.profile (id, name, role, bio, location, email, github, linkedin, website)
values (
  1,
  'Grish Pradhan',
  'Cybersecurity · Forensics · Systems',
  'I build practical tools and secure systems across cybersecurity, forensics, and software.',
  'Lalitpur, Nepal',
  '',
  'https://github.com/Grish-Pradhan',
  'https://www.linkedin.com/in/grish-pradhan-bb60b2279/',
  ''
)
on conflict (id) do nothing;

alter table public.profile enable row level security;
alter table public.projects enable row level security;
alter table public.messages enable row level security;

drop policy if exists "Public profiles are viewable by everyone" on public.profile;
drop policy if exists "Admins can update profile" on public.profile;
drop policy if exists "Projects are viewable by everyone" on public.projects;
drop policy if exists "Admins can manage projects" on public.projects;
drop policy if exists "Anyone can insert messages" on public.messages;
drop policy if exists "Admins can view messages" on public.messages;

create policy "Public profiles are viewable by everyone"
  on public.profile for select to anon, authenticated
  using (true);

create policy "Projects are viewable by everyone"
  on public.projects for select to anon, authenticated
  using (true);

revoke all privileges on table public.profile, public.projects, public.messages
  from anon, authenticated;
grant usage on schema public to anon, authenticated, service_role;
grant select on table public.profile, public.projects to anon, authenticated;
grant all privileges on table public.profile, public.projects, public.messages to service_role;
grant usage, select on all sequences in schema public to service_role;

commit;